### ISSUE TITLE
Reword ZenCache activation error message when Quick Cache is active

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#10]
Forked from #9.

Need to reword/improve the ZenCache Dashboard message that appears when Quick Cache is also active.

![2014-11-28_17-19-50](https://cloud.githubusercontent.com/assets/53005/5232604/d4a6e0a6-7722-11e4-940d-bc74b45c21ba.png)

This would be an improvement: 

> "**ZenCache** is NOT running. A conflicting plugin, **Quick Cache**, is currently active. Please deactivate the Quick Cache plugin to clear this message."

**Comment by jaswsinc** [comment]
Working on this now.

![2015-01-01_06-17-17](https://cloud.githubusercontent.com/assets/1563559/5592474/e2264ad0-917d-11e4-905b-19719fbccc78.png)
