### ISSUE TITLE
Plugin activation message to direct users to settings page

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#112]
There should be a helpful plugin activation message that directs users to the settings page to configure/enable Quick Cache after activation.

**Comment by jaswrks** [comment]
## Next Actions
- New feature branch in the `websharks/zencache-pro` repo.
- After [this line](https://github.com/websharks/zencache-pro/blob/151105-RC/src/includes/classes/Plugin.php#L255) add the following:
  
  ``` php
  'welcomed' => '0', // `0|1` welcomed yet?
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/7ab1eb1b9e57c1c1c40a68f585b76fe79caa5b11/src/includes/closures/Plugin/InstallUtils.php#L13) add the following:
  
  ``` php
  if (!$self->options['welcomed']) {
      $settings_url = add_query_arg(urlencode_deep(array('page' => GLOBAL_NS)), network_admin_url('/admin.php')));
      $self->enqueueMainNotice(sprintf(__('<strong>%1$s</strong> successfully installed! :-) Please <a href="%2$s">enable page caching</a> and configure options.', SLUG_TD), esc_html(NAME), esc_attr($settings_url), array('push_to_top' => true));
      $self->updateOptions(array('welcomed' => '1'));
  }
  ```
- Submit PR.

**Comment by kristineds** [comment]
@jaswsinc @raamdev I tried testing it on my demo site ~ encountered some parse errors but I fixed it (I think). I saw the activation message once but when I tried redoing it, I can't see it anymore. :(  https://github.com/websharks/zencache-pro/commit/786dff55e9e069e1fb9d6be13b8e7a834f2387a8

**Comment by raamdev** [comment]
@kristineds Try disabling Plugin Deletion Safeguards in **ZenCache → Plugin Options → Plugin Deletion Safeguards** and then deleting and uninstalling ZenCache. Then go in and install your modified version again. 

It sounds to me like the `welcomed` option value got saved as `1`, so you didn't see it show up again.

Let me know when you've run this through a successful test and I'll do some testing of my own. :-)

**Comment by kristineds** [comment]
@raamdev Great! It works now! :) Submitting my PR for this. cc @jaswsinc 
- https://github.com/websharks/zencache-pro/pull/175

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: When activating ZenCache for the first time, a new Dashboard message now includes a helpful link to the options page to enable caching and review the options. Props @kristineds. See [Issue #112](https://github.com/websharks/zencache/issues/112).

**Comment by raamdev** [comment]
**ZenCache Pro v151220** has been released and includes changes worked on as part of this GitHub Issue. See the [release announcement](http://zencache.com/zencache-pro-v151220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#112).
