### ISSUE TITLE
Fix caching support for bbPress

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#168]
As of v140520-RC, Quick Cache caches pages related to bbPress, but does not purge cache files related to bbPress when certain events take place (such as the creation of a new Forum).

Quick Cache needs to be updated to properly support bbPress.

Reported here: http://wordpress.org/support/topic/bbpress-new-replies-doesnt-auto-purging-cache

**Comment by raamdev** [comment]
Also reported here:
- https://websharks.zendesk.com/agent/tickets/6199

---

@jaswsinc writes...

> If user-specific caching is on, and a user does a `POST` of any kind, it wipes the cache for that user.

It wipes the cache for _that_ user (the one doing the `POST`), but not for any other users. So that means if logged-in user creates a new Topic, other logged-in users will not see that new topic until they logout and then back in (at which point their user cache will be cleared). Until that time (or until the entire cache is cleared automatically or manually), other logged-in users will be seeing stale versions of the site--newly created topics or comments made by other logged-in users (or for that matter, anonymous users) will never be seen until the user's cache is cleared.

## What needs to happen to improve bbPress support:

### When a new Forum is created
- Clear the cache for the Forums index (e.g., `/forums.html`)
- Clear the cache for all user caches for the Forums index (e.g., `forums.u/*.html`)

### When a new Topic is created in a Forum
- Clear the cache for that Forum index (e.g., `/forums/forum/example-forum.html`)
- Clear the cache for all user caches for that Forum index (e.g., `/forums/forum/example-forum.u/*.html`)

### When a new reply to a Topic is created
- Clear the cache for that Topic (e.g., `/forums/topic/example-topic.html`)
- Clear the cache for all user caches for that Topic (e.g., `/forums/topic/example-topic.u/*.html`)

---

@jaswsinc does that look right to you?

**Comment by xberg** [comment]
Hi,
I am having exactly the same issue with SimplePress (a competing WP forum plugin) and would expect the same solution. I am not too concerned about the first point, ie "when a new forum is created" as this happens once every blue moon and admin can easily clear the cache at that point. But the others happen all the time.

**Comment by raamdev** [comment]
@xberg Thank you for chiming in. We'll be sure to look into [SimplePress](http://simple-press.com/) compatibility when working on this issue.

**Comment by jaswrks** [comment]
> @jaswsinc does that look right to you?

Excellent, yes! That should do the trick.

**Comment by jaswrks** [comment]
This has been resolved in my dev branch: `feature/jaswsinc`. I'll submit a PR soon.

**Comment by jaswrks** [comment]
Line that fixes this issue: https://github.com/websharks/zencache-pro/commit/1b25d077fc7646ccf2cb7b84ed4ad2835c5b998d#diff-a5f584d3f31b9aff3ad43f0137497d98R103

The rest of the changes were an overall improvement and bbPress compat. enhancements.

**Comment by xberg** [comment]
Good news for bbpress. 
Is there anything I can document to make this happen with Simple Press as well?

**Comment by raamdev** [comment]
@xberg I have opened a separate GitHub issue for investigating Simple:Press compatibility; see https://github.com/websharks/zencache/issues/534. If you'd like to help out, please see my notes on that GitHub issue and leave follow-up comments related to Simple:Press over there. :-) Thanks!

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **bbPress Compatibility**: This release greatly improves compatibility with bbPress. Events like creating a new Forum, creating a new Topic, and posting a reply to a Topic (including threaded replies), now properly clear the necessary cache files to ensure that cached bbPress pages remain up-to-date. See [Issue #168](https://github.com/websharks/zencache/issues/168).

**Comment by raamdev** [comment]
**ZenCache Pro v150821** has been released and includes changes from this GitHub Issue.

See the [ZenCache Pro v150821 announcement](http://zencache.com/zencache-pro-v150821-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#168).
