### ISSUE TITLE
Throughput Graph (powered by waffle.io)

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache#19]
Attach our Throughput Graph, provided by waffle.io to the README.md.

---

### Throughput Graph (powered by waffle.io)

[![Throughput Graph](https://graphs.waffle.io/websharks/zencache/throughput.svg)](https://waffle.io/websharks/zencache/metrics)

**Comment by raamdev** [comment]
Merged PRs. Thanks! :)
