### ISSUE TITLE
Feature Request: Option to disable caching for Home Page / Posts Page

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#191]
It would be nice if there was a simple option to disable caching for the Home Page and/or the Posts page, if a site owner wanted to that. 

Excluding the Home Page from the cache is not currently possible without manually adding PHP code to the theme template to define `DONOTCACHEPAGE`. Using the URI Exclusions Feature wouldn't work because the exclusion pattern of `/` would exclude everything on the site.

**Comment by jaswrks** [comment]
Another way you could do this is from the `wp-config.php` file.

``` php
if(preg_match('/^\/(index\.php\/?)?(\?|$)/', $_SERVER['REQUEST_URI']))
    define('ZENCACHE_ALLOWED', FALSE); // Don't cache home page.
```

_This could also be done via `.htaccess` using mod_rewrite too._

---

I think it would be good for us to support a raw regex pattern in the list of URI/Referer/User-Agent exclusions where we currently support only the `*` wildcard character. I'm thinking of an alternate, more advanced syntax for those who need it; where a line can optionally start with `regex:` to indicate that it's a raw regular expression that should not be escaped like others are by default.

The default pattern matching is more of an `fnmatch()` style approach to keep it easy to work with for novice site owners; but adding some additional support here for regex would be great IMO. The underlying exclusion checks already use regex, so we just need to add a syntax variation I think.

**Comment by jaswrks** [comment]
Actually, I just remembered that this constant could also be configured manually if you prefer. So this is also possible using the `/wp-config.php` file if you prefer; even in the current release.

Put the following into your `/wp-config.php` file...

``` php
define('ZENCACHE_EXCLUDE_URIS', '/^\/(index\.php\/?)?(\?|$)/');
```

**Comment by jaswrks** [comment]
A more simplified variation, this doesn't cover as many edge cases.

``` php
define('ZENCACHE_EXCLUDE_URIS', '/^\/(\?|$)/');
```

**Comment by raamdev** [comment]
Noting that I had two requests for this feature today via ZenCache Pro support.

**Comment by jaswrks** [comment]
## Next Actions (Step 1 of 2)

_Referencing: https://gist.github.com/jaswsinc/8dedeb364a010ccdd8d0 and https://github.com/websharks/team/issues/29_
- New feature branch: `feature/191-step-1` in the `websharks/zencache-pro` repo.
- In [this directory](https://github.com/websharks/zencache-pro/tree/151004/src/includes/closures/Plugin), create a new file named: `PatternUtils.php`
  
  ``` php
  <?php
  namespace WebSharks\ZenCache\Pro;
  /*
  * Convert line-delimited patterns to a regex.
  *
  * @since 15xxxx Enhancing exclusion pattern support.
  *
  * @param string $patterns Line-delimited list of patterns. 
  *
  * @return string A `/(?:list|of|regex)/i` patterns.
  */
  $self->lineDelimitedPatternsToRegex = function ($patterns) use ($self) {
      $regex    = ''; // Initialize.
      $patterns = (string)$patterns;
  
      if (($patterns = preg_split('/['."\r\n".']+/', $patterns, null, PREG_SPLIT_NO_EMPTY))) {
          $regex = '/(?:'.implode(
              '|',
              array_map(
                  function ($string) {
                      return preg_replace(
                          array(
                              '/\\\\\^/',
                              '/\\\\\*\\\\\*/',
                              '/\\\\\*/',
                              '/\\\\\$/',
                          ),
                          array(
                              '^', // Beginning of line.
                              '.*?', // Zero or more chars.
                              '[^\/]*?', // Zero or more chars != /.
                              '$', // End of line.
                          ),
                          preg_quote($string, '/')
                      );
                  },
                  $patterns
              )
          ).')/i';
      }
      return $regex;
  };
  ```
- Replace [these lines of code](https://github.com/websharks/zencache-pro/blob/151004/src/includes/closures/Plugin/InstallUtils.php#L294-L307) with the following:
  
  ``` php
  $_value = "'".$self->escSq($self->lineDelimitedPatternsToRegex($_value))."'";
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/151004/src/includes/classes/VsUpgrades.php#L278) add the following:
  
  ``` php
  /**
  * Before we changed the way exclusion patterns work.
  *
  * @since 15xxxx Enhancing exclusion patterns.
  */
  protected function fromLte151006()
  {
      if (version_compare($this->prev_version, '150807', '<=')) {
          if (is_array($existing_options = get_site_option(GLOBAL_NS.'_options'))) {
              if (!empty($existing_options['exclude_uris'])) {
                  $this->plugin->options['exclude_uris'] = str_replace('*', '**', $existing_options['exclude_uris']);
              }
              if (!empty($existing_options['exclude_refs'])) {
                  $this->plugin->options['exclude_refs'] = str_replace('*', '**', $existing_options['exclude_refs']);
              }
              if (!empty($existing_options['exclude_agents'])) {
                  $this->plugin->options['exclude_agents'] = str_replace('*', '**', $existing_options['exclude_agents']);
              }
              if (!empty($existing_options['htmlc_css_exclusions'])) {
                  $this->plugin->options['htmlc_css_exclusions'] = str_replace('*', '**', $existing_options['htmlc_css_exclusions']);
              }
              if (!empty($existing_options['htmlc_js_exclusions'])) {
                  $this->plugin->options['htmlc_js_exclusions'] = str_replace('*', '**', $existing_options['htmlc_js_exclusions']);
              }
              if ($this->plugin->options !== $existing_options) {
                  $this->plugin->updateOptions($this->plugin->options); // Save/update options.
              }
          }
      }
  }
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/151004/src/includes/classes/VsUpgrades.php#L47) add the following:
  
  ``` php
  $this->fromLte151006();
  ```
- Submit PR.

**Comment by jaswrks** [comment]
## Next Actions (Step 2 of 2)
- New feature branch `feature/191-step-2` in the `websharks/zencache-pro` repo.
- In [this file](https://github.com/websharks/zencache-pro/blob/151004/src/includes/classes/MenuPageOptions.php) go through all of the relevant config. options; i.e., those that accept patterns, and update the inline documentation with [details](https://gist.github.com/jaswsinc/8dedeb364a010ccdd8d0) about this new syntax.
  
  ##### New Syntax
  
  ``` text
  ^    = Beginning of line.
  *    = Zero or more chars that are NOT a / slash.
  **   = Zero or more chars of any kind, including a / slash.
  $    = End of the line.
  ```
  
  ![2015-10-06_23-20-07](https://cloud.githubusercontent.com/assets/1563559/10331349/1975d530-6c81-11e5-8052-ef509d35b07d.png)
  
  ---
  
  ![2015-10-06_23-19-17](https://cloud.githubusercontent.com/assets/1563559/10331348/19751a32-6c81-11e5-8752-91c152cc0e99.png)
  
  ---
  
  ![2015-10-06_23-20-42](https://cloud.githubusercontent.com/assets/1563559/10331350/19777192-6c81-11e5-9a1d-a8038fec2f1e.png)
- Submit PR.

**Comment by jaswrks** [comment]
@kristineds While working on this issue you can take note of what Regex is and why it is a crucial piece of the puzzle whenever you are working to enhance your skills as a developer. Regular Expressions are a language of their own, but they are vital in almost every programming language that deals with string manipulation; i.e., almost all of them.
- This is a great place to practice Regex: https://regex101.com/
- I learned regex a few years ago with a lot of help from this site: http://www.regular-expressions.info/

We deal almost exclusively with PCRE (Perl-Compatible Regular Expressions). So whenever you seek information to help you write regex patterns and/or understand what you're looking at, you can put your focus on articles that discuss PHP's `preg_*()` (PCRE) functions and sites that discuss PCRE in general.

Once you understand PCRE and how to work with regex in PHP, you'll have no trouble [adapting that knowledge whenever you work in JavaScript, Ruby, Python, etc.](http://www.bitcetera.com/page_attachments/0000/0030/regex_in_a_nutshell.pdf).

Referencing: http://php.net/manual/en/ref.pcre.php The most important PCRE functions in PHP are:
- http://php.net/manual/en/function.preg-match.php
- http://php.net/manual/en/function.preg-replace.php

**Comment by raamdev** [comment]
@kristineds Ping. ↑ Just wondering when you'll be able to get around to submitting a PR for step 2 above so that I can close this issue before the next release RC deadline of October 22nd.

**Comment by kristineds** [comment]
@raamdev I just submitted the PR for step 2. Please refer to the latest commit for the updated version. Would love to hear your feedback on this and how to proceed. Thanks! cc @jaswsinc

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **New Feature!** A new watered-down Regular Expression syntax is now supported in several existing ZenCache features, including the new list of Custom URLs to Auto-Clear, URI Exclusion Patterns, HTTP Referrer Exclusion Patterns, User-Agent Exclusion Patterns, and the HTML Compressor CSS Exclusion Patterns and JavaScript Exclusion Patterns. This new syntax greatly increases the power and flexibility of each of these features and makes things possible like the much-requested ability to Auto-Clear the Home Page or Posts Page of a site whenever a post cache is cleared. For more information on this new watered-down Regular Expression syntax, [this KB Article](http://zencache.com/r/watered-down-regex-syntax/). Props @kristineds @jaswsinc. See [Issue #191](https://github.com/websharks/zencache/issues/191).

**Comment by raamdev** [comment]
**ZenCache v151114** has been released and includes changes from this GitHub Issue. See the [v151114 announcement](http://zencache.com/zencache-pro-v151114-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#191).
