### ISSUE TITLE
Feature Request: Load JS/CSS in footer

### ISSUE THREAD

**Issue by marcobax** [websharks/zencache#248]
Having an admin option (checkbox) for these options:
Load compressed javascript files in footer [yes/no]
Load compressed CSS files in footer [yes/no](should be loaded first)

This can improve a score for tools like Google Pagespeed, because they require javascript and/or CSS files to be loaded into the footer, say: just before the closing <body> tag.

**Comment by raamdev** [comment]
Referencing related KB Article: [Why doesn't ZenCache move CSS/JS scripts into the footer?](http://zencache.com/kb-article/why-doesnt-zencache-move-cssjs-into-the-footer/)

**Comment by raamdev** [comment]
See also (KB Article draft): [Why doesn't the HTML Compressor defer render-blocking JavaScript?](https://github.com/websharks/comet-cache-kb/issues/28)
