### ISSUE TITLE
Fatal Error during uninstall

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#25]
`uninstall.php` requires `/includes/wp-php53.php`, but that file doesn't exist (it is now `wp-php-rv.php`).

**Note that this also affects ZenCache Pro.**

![2015-02-04_22-28-34](https://cloud.githubusercontent.com/assets/53005/6054594/7886f3ee-acbd-11e4-914d-650a10c19f3d.png)

**Comment by jaswsinc** [comment]
Great catch! I submitted two PRs that correct this issue in both the lite/pro versions.

**Comment by raamdev** [comment]
> I submitted two PRs

Merged. Thank you!
