### ISSUE TITLE
"Plugin Updater" didn't work

### ISSUE THREAD

**Issue by bridgeport** [websharks/zencache#252]
Hi,

This is more of an FYI report, as I don't really need a resolution to this issue due to my having a workaround.

Using WordPress v3.9.1 on Apache server. Tried upgrading from Quick Cache Pro v140605 to v140725 using the built-in "plugin updater" failed.

There was a dashboard notice that a new Pro version was available. I went to the plugin updater page, entered my username and license key (in place of the password), then initiated the update.

Because my site uses SFTP to perform plugin upgrades, the upgrade process was interrupted (appropriately) by a screen prompting me for my SFTP username and password. After supplying these credentials and resubmitting the page, the following notice was shown:

`Update Plugin - The plugin is at the latest version.`

But Quick Cache Pro was still at v140605, no files were updated, and the dashboard notification (of an updated version) was no longer available. So, it appears that Quick Cache's internal processes thinks I was at the latest version even though it's still showing v140605 on the plugin page. Trying to force another upgrade through the "plugin update" resulted in the same "Update Plugin - The plugin is at the latest version." notice.

I ultimately deactivated, deleted, then installed v140725 through the traditional plugin upload route. That also required SFTP (as all plugin installations do), but that worked fine. And since my Deactivation Safeguards were previously in place, my settings were maintained.

I have no problem manually deactivating, deleting, and uploading new versions of Quick Cache Pro as it's still a fast process.

By the way, the plugin updater did work on my Windows development environment using the same username/license key credentials. The test environment (WordPress and plugins) is the same as the Apache environment.

Thanks.

**Comment by raamdev** [comment]
@bridgeport Can you confirm that you're still having this SFTP issue with the latest version of ZenCache? There were a few bug fixes since this GitHub Issue was created that addressed some issues related FTP/SFTP, so I'm thinking this issue can be closed but I wanted to double-check with you first.

**Comment by bridgeport** [comment]
@raamdev It works great now. Update via SFTP went off without a hitch. In the time between my opening this ticket, I've had to install the "SSH SFTP Updater Support" plugin ( https://wordpress.org/plugins/ssh-sftp-updater-support/ ) due to changing firewall settings.

With that in place, updating still went fine.

Thanks.

**Comment by raamdev** [comment]
@bridgeport Thank so much for the update! :-) I'll go ahead and close this issue.
