### ISSUE TITLE
Import Settings from Quick Cache (Lite)

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#26]
Quick Cache (Lite) doesn't have the option to Import/Export its plugin options, so for people migrating from Quick Cache to ZenCache (which will be a much higher number than Quick Cache Pro → ZenCache Pro), it would be very nice to have the Quick Cache options automatically copied over to ZenCache when it is activated. 

I consider this a priority item for the initial public launch because we want to reduce the friction of migrating as much as possible. If site owners are told they'll have to re-apply any settings they changed in Quick Cache, they may just give up and not migrate at all (since many might not know IF they changed any settings and would rather not change something that's already working fine).

---
#### ZenCache ⥱ Plugin Options ⥱ Enable/Disable

- [ ] Import Quick Cache `debugging_enable` settings

#### ZenCache ⥱ Plugin Options ⥱ Plugin Deletion Safeguards

- [ ] Import Quick Cache `uninstall_on_deletion`

#### ZenCache ⥱ Plugin Options ⥱ Directory / Expiration Time

- [ ] Import Quick Cache `base_dir`, but _only_ if it's **not** set to the Quick Cache default of `cache/quick-cache` (i.e., they have changed this setting, so we want to preserve the change)
- [ ] Import Quick Cache `cache_max_age` 

#### ZenCache ⥱ Plugin Options ⥱ Client-Side Cache

- [ ] Import Quick Cache `allow_browser_cache`

#### ZenCache ⥱ Plugin Options ⥱ GET Requests

- [ ] Import Quick Cache `get_requests`

#### ZenCache ⥱ Plugin Options ⥱ 404 Requests

- [ ] Import Quick Cache `cache_404_requests`

#### ZenCache ⥱ Plugin Options ⥱ RSS, RDF, and Atom Feeds

- [ ] Import Quick Cache `feeds_enable`

**Comment by jaswsinc** [comment]
I think we have already covered this. Please see http://youtu.be/aXrvnNU7V_I, and then let me know if you still feel this is necessary.

**Comment by raamdev** [comment]
> I think we have already covered this. Please see http://youtu.be/aXrvnNU7V_I, and then let me know if you still feel this is necessary.

Yup, this is all set. Thanks for the video! :-)
