### ISSUE TITLE
Show Dashboard message when migrating from Quick Cache

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#28]
When ZenCache is activated and detects an active Quick Cache plugin, it copies the Quick Cache settings, deactivates Quick Cache, and then activates itself.

However, this happens silently and there is no indication or notification about any of this happening.

We need a Dashboard message that triggers at the end of the version-specific upgrade routine `from_quick_cache()` (assuming existing Quick Cache options were detected and cleaned up).

I suggest the following:

![2015-02-06_20-11-06](https://cloud.githubusercontent.com/assets/53005/6090073/55cccee8-ae3c-11e4-8900-c32e3a25785b.png)

**Comment by jaswsinc** [comment]
Initial thoughts...

- Too much information. I'd try to keep it at one or two lines.
- The word "successor". It makes total sense of course, but I wonder how many people will really comprehend that in the 1.25 seconds they spend looking at that message.

Woohoo! ZenCache activated :-) NOTE: Your Quick Cache options were preserved by ZenCache.  You haven't lost a thing. Please see: [ZenCache ⥱ Plugin Options](link here).

**Comment by raamdev** [comment]
> Too much information.

Yeah, that was my feeling too.

However, here are a few things I feel are important to convey:

- Quick Cache was deactivated and it's okay to delete that plugin now _("Can I delete Quick Cache now?" is going to be a common question after installing ZenCache.)_
- Quick Cache options were preserved by ZenCache _("Were my custom Quick Cache settings preserved?")_
- Link to visit ZenCache settings. _(This is important IMO mostly because the Quick Cache menu item is still visible right after activating ZenCache. If somebody clicks on the Quick Cache menu item after activating ZenCache, they'll get a "Permission denied" error from WordPress... so we want to encourage them to go _somewhere_ right after updating, so that upon the next screen refresh that Quick Cache menu item is gone.)_
- Link to an announcement post or FAQ article where the can see answers to other questions they may have, which we can update as people start asking questions we didn't think of. _(This is somewhat optional in my mind, but it would be really nice to have.)_

**Comment by raamdev** [comment]
Also, there's already a "Plugin activated" message that will show up above whatever additional message we add, hence the reason I left out "ZenCache has been activated".

Here's what the site owner will see right after activating ZenCache, when Quick Cache was previously active:

![2015-02-06_20-38-28](https://cloud.githubusercontent.com/assets/53005/6090223/4a780716-ae40-11e4-813c-8752fd8a6d55.png)

**Comment by raamdev** [comment]
Still too noisy?

![2015-02-06_20-58-01](https://cloud.githubusercontent.com/assets/53005/6090327/e14d3e2a-ae42-11e4-8efe-56385bb8ef56.png)

**Comment by jaswsinc** [comment]
I see. All great points. Well, I don't have an issue with what you have there, so if you think that's better, it's perfectly OK with me. I completely agree that it's a good idea to answer as much as we can through the process itself. Perhaps it would help to more put focus on a specific link in that notice; one which leads to an article that goes over this specific scenario. That way as questions come in, we can alter that remotely, so it answers the questions we are actually getting; i.e. things we might not realize will be asked, but can identify as soon as they start to come in.

My only concern is this. If a user does the update and sees that it's all rather complex, and there are several details that you need to read over before you're really able to understand what's happened; it makes it harder to write an article about the update process. In short, it makes it harder for others to spread the word by saying, "wow, it was so quick/easy".

I'd put the primary focus on a.) what you got by upgrading; e.g. new UI, new features. b.) a link to an article that goes over the specifics.

So something like, "you can safely delete Quick Cache now. See [this article]() for further details.

**Comment by jaswsinc** [comment]
> Still too noisy?

Ha.. that's perfect.

**Comment by raamdev** [comment]
I figure if we just get ONE link in there that makes it obvious they can get answers to frequently asked questions, then if they're wondering if they can delete Quick Cache, they'll go there to find out... etc.

**Comment by raamdev** [comment]
We should do the same thing for ZenCache Pro, agreed? (Changing "Quick Cache" to "Quick Cache Pro" and "ZenCache" to "ZenCache Pro"...)

**Comment by jaswsinc** [comment]
> We should do the same thing for ZenCache Pro, agreed? (Changing "Quick Cache" to "Quick Cache Pro" and "ZenCache" to "ZenCache Pro"...)

Agreed :-)

**Comment by raamdev** [comment]
![2015-02-06_21-45-56](https://cloud.githubusercontent.com/assets/53005/6090589/9fe7ebba-ae4c-11e4-905d-3d6d5e41950a.png)

**Comment by ioerjfoige0439i** [comment]
Can we just delete Quick Cache before installing Zen Cache? I still have W3 Total Cache installed and have ever activated Quick Cache since you can't have two caching plugins installed at one time. Would it be safe to just delete W3 Total Cache before uploading and activating Zen Cache? (also does this soft release have CDN?) Thanks!

**Comment by raamdev** [comment]
> Can we just delete Quick Cache before installing Zen Cache?

Sure. As long as you don't have any existing Quick Cache settings you want ZenCache to import, then deleting Quick Cache first will be no problem.

> would it be safe to just delete W3 Total Cache before uploading and activating Zen Cache?

Yes, that would fine fine as well.

> also does this soft release have CDN?

Yes, ZenCache Pro will include CDN support.
