### ISSUE TITLE
"Fatal Error: 'Unable to clear dir'"

### ISSUE THREAD

**Issue by nigelp** [websharks/zencache#288]
Wow, way to go to make paying customers jump through a million hoops to file a bug report on your paid products Jason. Not awesome. 

Anyway, I'm getting a weird one with Quick Cache Pro. It's fairly benign (in that it doesn't corrupt or delete anything), but it is annoying. 
1. Action: Post or edit a post on the site
2. Press the Publish or Save As Pending Button
3. Expected behaviour - saved and return to page
   Accual (intermittent) behaviour - see attached image pops up. 

The problem doesn't happen all the time, maybe 20% of the time. 

Thanks. 

Nigel P.
![cacheerror](https://cloud.githubusercontent.com/assets/97901/4058544/64a9f07a-2dd7-11e4-8bd6-f5940e5d4d45.jpg)

**Comment by mchlbrry** [comment]
@raamdev, here are the errors I can see:

```
[08-Jan-2015 21:17:03 UTC] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'SplFileInfo::getMTime(): stat failed for /var/www/html/kysadmn/wp-content/cache/quick-cache/cache/http/www-killyourstereo-com-54aef3cf69cc8928126844-tmp/album-of-the-year-2013.html' in /var/www/html/kysadmn/wp-content/plugins/quick-cache-pro/includes/share.php:1675
Stack trace:
#0 /var/www/html/kysadmn/wp-content/plugins/quick-cache-pro/includes/share.php(1675): SplFileInfo->getMTime()
#1 /var/www/html/kysadmn/wp-content/plugins/quick-cache-pro/includes/share.php(1462): quick_cache\share->delete_files_from_host_cache_dir('/^.+/i', true)
#2 /var/www/html/kysadmn/wp-content/plugins/quick-cache-pro/quick-cache-pro.inc.php(1291): quick_cache\share->purge_files_from_host_cache_dir('/^.+/i')
#3 [internal function]: quick_cache\plugin->purge_cache()
#4 /var/www/html/kysadmn/wp-includes/plugin.php(580): call_user_func_array(Array, Array)
#5 /var/www/html/kysadmn/wp-cron.php(103): do_action_ref_array('_cron_quick_cac...', Array)
#6 {main}
  thrown in /var/www/html/kysadmn/wp-content/plugins/quick-cache-pro/includes/share.php on line 1675
```

**Comment by raamdev** [comment]
@mchlbrry Thank you for the errors. I've opened a new Issue (#397 _Temp Files in Cache Directory Fail to Clear_) to continue tracking this bug, as this particular issue (#288) is getting a bit long. I've copied your error report over there. 

Please follow Issue #397 for further updates.

**Comment by raamdev** [comment]
**Quick Cache v150121 (Release Candidate)** was released yesterday that includes further fixes for this issue. If you'd like to help test the Release Candidate, that would be greatly appreciated! Please see http://www.websharks-inc.com/post/quick-cache-v150121-release-candidate/

---

Please report future any updates to this issue (_"Fatal Error: 'Unable to clear dir'"_) on Issue #397.
