### ISSUE TITLE
Refactor codebase to utilize delete_files_from_host_cache_dir()

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#317]
Routines in the Quick Cache codebase that delete cache files for the current host should be refactored to use `delete_files_from_host_cache_dir()` (see [includes/share.php#L1066](https://github.com/websharks/quick-cache/blob/000000-dev/quick-cache/includes/share.php#L1066)).

---

### Related Issues

- [Refactor codebase to utilize purge_files_from_host_cache_dir()](https://github.com/websharks/quick-cache/issues/318)
- [Refactor codebase to utilize clear_files_from_host_cache_dir()](https://github.com/websharks/quick-cache/issues/319)
- Forked from #288

**Comment by jaswrks** [comment]
I think this could be closed now. I'm not aware of any remaining work being needed to complete the task that was listed in this issue. We covered this a while back.

**Comment by raamdev** [comment]
Got it. Thank you!
