### ISSUE TITLE
Refactor codebase to utilize clear_files_from_host_cache_dir()

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#319]
To help make Quick Cache DRYer, we should consolidate various cache clearing routines into a single `clear_files_from_host_cache_dir()`()`.

---

### TODO

- [ ] Write `clear_files_from_host_cache_dir()`; should probably live in `includes/share.php`
- [ ] Refactor any cache clearing routines in the Quick Cache codebase to use the new `clear_files_from_host_cache_dir()`

---

### Related Issues

- [Refactor codebase to utilize delete_files_from_host_cache_dir()](https://github.com/websharks/quick-cache/issues/317)
- [Refactor codebase to utilize purge_files_from_host_cache_dir()](https://github.com/websharks/quick-cache/issues/318)
- Forked from #288

**Comment by jaswrks** [comment]
I think this could be closed now. I'm not aware of any remaining work being needed to complete the task that was listed in this issue. We covered this a while back.

**Comment by raamdev** [comment]
> I think this could be closed now. I'm not aware of any remaining work being needed to complete the task that was listed in this issue. We covered this a while back.

Got it. Thank you!
