### ISSUE TITLE
Update icon for WordPress Plugin Repository Browser

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#33]
The plugin icon is currently set to this:
![icon-256x256](https://cloud.githubusercontent.com/assets/53005/6181581/3f1399c2-b303-11e4-8b8a-3c406d057258.png)

We should use something more colorful: 

![icon-](https://cloud.githubusercontent.com/assets/53005/6181663/63df3ec2-b304-11e4-817a-a099c422ed49.png)

But there's another reason for changing the icon: We want people already familiar with Quick Cache to recognize ZenCache. With similar logos / colors, it will be easier for them to make the connection:

![2015-02-12_22-16-18](https://cloud.githubusercontent.com/assets/53005/6181698/ecfbbafa-b304-11e4-884c-5d74b5f005b7.png)

---

Need `icon-128x128.png` and `icon-256x256.png`.

**Comment by raamdev** [comment]
### `icon-128x128.png`

![icon-128x128](https://cloud.githubusercontent.com/assets/53005/6191136/434f54aa-b375-11e4-8099-f23f36416a10.png)

### `icon-256x256.png`
![icon-256x256](https://cloud.githubusercontent.com/assets/53005/6191140/47d2f374-b375-11e4-8fae-68de1cc9ea60.png)

### `icon-color.sketch`

https://cloudup.com/cv9f1B8ls0Q

### Preview of the icon in the plugin repo browser

![2015-02-13_11-41-03](https://cloud.githubusercontent.com/assets/53005/6191152/6963c84c-b375-11e4-9898-4abe4b451ce0.png)

**Comment by jaswsinc** [comment]
Love the green! The color of money.
