### ISSUE TITLE
Compatibility With WP-SESSION plugin

### ISSUE THREAD

**Issue by ethanpil** [websharks/zencache#34]
I am running the latest versions of both WP-Session and QuickCache

https://github.com/ericmann/wp-session-manager

It seems that one of the two plugins is jumping the gun on the cookies in HTTP header...

I keep getting:

:  Cannot modify header information - headers already sent by (output started at /srv/public_html/wp-content/advanced-cache.php:1137) in /srv/public_html/wp-content/plugins/wp-session-manager/includes/class-wp-session.php

**Comment by raamdev** [comment]
@ethanpil Could you please open this issue under the Quick Cache repo? http://github.com/websharks/quick-cache/issues/
