### ISSUE TITLE
Feature Request: Prevent Cache Expiration on high Server Load

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#347]
Requested [on WordPress.org](https://wordpress.org/support/topic/some-suggestions-29?replies=1#post-6081899):

> If the Server Load is greater than a number, DO NOT expire the cached page but serve it from the cache.

Such a feature, utilizing the PHP [`sys_getloadavg()`](http://php.net/manual/en/function.sys-getloadavg.php) function, would only work in non-Windows hosting platforms, but nevertheless we could detect if `sys_getloadavg()` works on the current platform and then provide options for letting a site owner configure a specific server-load at which Quick Cache should _not_ allow cache expiration.

--- 

## Support threads referencing this issue

- https://wordpress.org/support/topic/some-suggestions-29?replies=1#post-6081899

**Comment by jaswrks** [comment]
This is ready for work IMO.
- [x] Add a new option in ZenCache Pro that enables this.
- [x] Add a new option that controls what should be considered too high of a load average; i.e., at what load should purging not occur.
- [x] Add a conditional check [here](https://github.com/websharks/zencache-pro/blob/000000-dev/zencache-pro/zencache-pro.inc.php#L1356) that stops before purging occurs whenever the load average is high.
- [x] Also prevent ZenCache from checking the age of existing cache files; i.e., update the AdvancedCache class.

**Comment by jaswrks** [comment]
A [new utility](https://github.com/websharks/zencache-pro/blob/feature/83/src/includes/closures/Plugin/SysUtils.php#L4-L26) was implemented in websharks/zencache-pro#127

``` php
/*
 * System load averages.
 *
 * @since 15xxxx Adding cache directory statistics.
 *
 * @return array System load averages.
 */
$self->sysLoadAverages = function () use ($self) {
    if (!is_null($averages = &$self->cacheKey('sysLoadAverages'))) {
        return $averages; // Already cached these.
    }
    if (!$self->functionIsPossible('sys_getloadavg')) {
        return ($averages = array());
    }
    if (!is_array($averages = sys_getloadavg()) || !$averages) {
        return ($averages = array());
    }
    $averages = array_map('floatval', $averages);
    $averages = array_slice($averages, 0, 3);
    // i.e., 1m, 5m, 15m; see: <http://jas.xyz/1gWyJLt>
    return $averages;
};
```

## Example Usage

``` php
$load_averages = $self->sysLoadAverages();
if ($load_averages) {
    // 1 minute ago = (float) $load_averages[0];
    // 5 minutes ago = (float) $load_averages[1];
    // 15 minutes ago = (float) $load_averages[2];
}
```

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **New Feature**: It's now possible to "Disable Cache Expiration If Server Load Average is High" (see _Dashboard → ZenCache → Plugin Options → Cache Expiration Time_). This allows you to provide a specific load average that should cause ZenCache to disable cache expiration and help reduce stress on the server; i.e., to avoid generating a new version of the cache while the server is very busy. Props @jaswsinc. See [Issue #347](https://github.com/websharks/zencache/issues/347).

**Comment by raamdev** [comment]
**ZenCache Pro v151002** has been released and includes changes from this GitHub Issue. 

See the [v151002 release announcement](http://zencache.com/zencache-pro-v151002-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#347).
