### ISSUE TITLE
BUG: disable clear/wipe cache not working

### ISSUE THREAD

**Issue by Alergic** [websharks/zencache#35]
hello ! this is the first issue I open on GitHub :) Or maybe I should have used a Pull Request ? I still don't know everything about how things works around here.

So, I just moved to ZenCache from Quick Cache, and found out that disable clear cache feature it's not working. I double checked all the steps for creating a MU plugin folder, a .php file, naming and everything was done as it should.
I enable a plugin... and see the message that cache files were cleared.
Is there anything you can do ?
Thank you !

**Comment by raamdev** [comment]
@Alergic Could you please copy/paste the MU plugin that you're using to disable automatic clearing routines?

**Comment by Alergic** [comment]
copy and paste with its name: zc-disable-auto-clear-wipe-cache-routines.php

and file content:
<?php
/*
Plugin Name: Disable ZenCache Clear and Wipe Cache Routines
Description: Disables all automatic ZenCache Clear and Wipe Cache Routines
Author: WebSharks, Inc.
Version: 1.0
Author URI: http://www.websharks-inc.com
*/

add_filter('zencache_disable_auto_wipe_cache_routines', '__zencache_disable_auto_clear_wipe_cache_routines', 10, 0);
add_filter('zencache_disable_auto_clear_cache_routines', '__zencache_disable_auto_clear_wipe_cache_routines', 10, 0);

function __zencache_disable_auto_clear_wipe_cache_routines() {
    return TRUE; // Yes, disable ZenCache Clear and Wipe Cache Routines
}

**Comment by jaswsinc** [comment]
@Alergic Are you running ZenCache Lite or ZenCache Pro? These filters applied by the MU plugin are specifically designed to work with ZenCache Pro.

**Comment by Alergic** [comment]
I am a Pro user !

**Comment by raamdev** [comment]
@Alergic Thank you. Can you tell me what you're doing when you see the cache get cleared? Are you installing a plugin? If so, can you tell me exactly how you're installing (uploading a zip file or installing via the WordPress Dashboard plugin repo?), and exactly when you see the message that the cache has been cleared?

If you could provide step-by-step instructions to recreate the problem, that would be helpful.

**Comment by Alergic** [comment]
Not much to say, I just activate a disabled plugin.

I backed up and also tested wipe cache after saving options of Zen Cache.
ZenCache: detected significant changes. Found 2855 files in the cache; auto-wiping.

An folder is indeed now empty.

**Comment by Alergic** [comment]
Just tested on a fresh subdomain, with default theme and wp-content folder.
`ZenCache: detected significant changes. Found 5 files in the cache; auto-wiping.`

Tested also on another site I have on a free ridiculous host. Messages shown right after upgrading to ZC, but using the mu-plugin file for QC:
`ZenCache: detected important site changes that would normally trigger a clear cache routine. However, clear cache routines have been disabled by a site administrator. [?]`
`ZenCache: detected significant changes that would normally trigger a wipe cache routine, however wipe cache routines have been disabled by a site administrator. [?]`

**Comment by jaswsinc** [comment]
@Alergic Have you been able to confirm that your MU plugin file is in fact loading? Given that it's in a non-standard location, it might good just to check on that. I suggest adding a test inside `public_html/continut/mu-plugins/zc-disable-auto-clear-wipe-cache-routines.php`

```php
<?php
if(!empty($_REQUEST['test']))
    exit('Yes, it loads!');
/*
Plugin Name: Disable ZenCache Clear and Wipe Cache Routines
Description: Disables all automatic ZenCache Clear and Wipe Cache Routines
Author: WebSharks, Inc.
Version: 1.0
Author URI: http://www.websharks-inc.com
*/

add_filter('zencache_disable_auto_wipe_cache_routines', '__zencache_disable_auto_clear_wipe_cache_routines', 10, 0);
add_filter('zencache_disable_auto_clear_cache_routines', '__zencache_disable_auto_clear_wipe_cache_routines', 10, 0);

function __zencache_disable_auto_clear_wipe_cache_routines() {
    return TRUE; // Yes, disable ZenCache Clear and Wipe Cache Routines
}
```

Then visit your site with `/?test=yes` on the end to confirm that "it loads!".

**Comment by raamdev** [comment]
@Alergic Thanks for the feedback and for the testing.

I was able to reproduce this in the latest version of ZenCache Pro (v150218) and using [the MU Plugin described on the wiki](https://github.com/websharks/quick-cache/wiki/Clear-Cache-and-Wipe-Cache-Routines#disable-both-clear-and-wipe-cache-routines) (the same as you shared above).

### Steps to Reproduce

- Install [MU Plugin to disable automatic clearing routines](https://github.com/websharks/quick-cache/wiki/Clear-Cache-and-Wipe-Cache-Routines#disable-both-clear-and-wipe-cache-routines)
- Install, activate, and enable ZenCache Pro.
- Visit the site as a logged-out user to generate some cache files
- From the WordPress Dashboard, modify a WordPress Setting (e.g., `Settings → General`, or `Settings → Permalinks`)

### Expected Behavior

I would expect to see a message from ZenCache indicating automatic clearing routines have been disabled.

### Observed Behavior

The cache is auto-cleared:

![2015-02-25_20-29-39](https://cloud.githubusercontent.com/assets/53005/6384645/5ef0c448-bd2d-11e4-842d-0d74a9a6441a.png)

**Comment by raamdev** [comment]
I should also note the following:

I was unable to reproduce this with anything other than changing WordPress Settings; installing, activating, and disabling plugins did not result in my cache being auto-cleared. However, I did not get any message from ZenCache indicating that the auto-clearing routines were disabled, which is what I would've expected.

**Comment by Alergic** [comment]
@jaswsinc 
I added the modified code, and I got a blank page with a single line "Yes, it loads!" 
Anyway, when I load the modules admin page, I have 1 plugin in mu-plugin section.

@raamdev 
Maybe you modified the code yesterday ? I tested again cache autoclearing on the main site, and enabling a plugin don't have any effect now. Don't know what to say.

But I don't understand why do you refer to Wiki QuickCache, and not using your latest documentation, as we are talking about ZenCache.
http://zencache.com/kb-article/disabling-automatic-clear-wipe-cache-routines/

**Comment by raamdev** [comment]
> Maybe you modified the code from here yesterday ? http://zencache.com/kb-article/disabling-automatic-clear-wipe-cache-routines/
> 
> But I don't understand why do you link to Wiki QuickCache, and not using your latest documentation, as we are talking about ZenCache. I suppose you didn't reproduced it with code from Quick Cache.

Sorry, that was my mistake. I linked to the Quick Cache Wiki page, but I was using and testing with the code from the ZenCache article: http://zencache.com/kb-article/disabling-automatic-clear-wipe-cache-routines/

I tested and reproduced this with ZenCache Pro v150218 as described above. I haven't modified any code is any of the documentation.

> I tested again cache autoclearing on the main site, and enabling a plugin don't have any effect now. Don't know what to say.

I'm not sure why that's working for you now, but it sounds like we're both seeing the exact same behavior: Enabling a plugin doesn't clear the cache, but it also doesn't show any notification that the cache wasn't cleared.

**Comment by Alergic** [comment]
It still remains the problem of autowiping cache, at least for my site. I assume that others with more knowledge than me have the same problem, and someone will find the way to reproduce it.
Thank you both for attention !

**Comment by jaswsinc** [comment]
Nice work reproducing this guys :-)

I think I found the underlying cause of this. The Quick Cache back compat. method `\zencache\share\apply_wp_filters()` was not passing the ZenCache-filtered value through the Quick Cache back compat. routine. 

So what was happening is that the value was being filtered to `TRUE`, then reset to `FALSE` and piped through a Quick Cache back compat. filter also. If the Quick Cache filter did not exist (it likely will not on a ZenCache installation), the value was essentially returned unfiltered; i.e., as the original value of `FALSE`.

I submitted a Pull Request to resolve this for the next release.

@Alergic @raamdev You can help by testing [this copy of `share.php`](http://bit.ly/1AMFvsC). Please use this file and let it replace your existing copy of `/zencache-pro/includes/share.php`. Then run your test again and see if that does the trick.

**Comment by jaswsinc** [comment]
Updated [this copy of `share.php`](http://bit.ly/1AMGrgN) link in my last post to point to the correct branch. It was previously pointing to the dev branch, when in fact it should have pointed to the branch for this issue.

**Comment by jaswsinc** [comment]
@Alergic  writes...

> Or maybe I should have used a Pull Request ?

A Pull Request is used to submit changes to the codebase.
https://help.github.com/articles/using-pull-requests/

**Comment by Alergic** [comment]
@jaswsinc Thx for the infos !
Problem solved ;) 
You definitely are two bright guys and make a great team. I am watching your blogs :)

 I can go back to my articles. All the best !

**Comment by raamdev** [comment]
> You can help by testing this copy of share.php. Please use this file and let it replace your existing copy of /zencache-pro/includes/share.php. Then run your test again and see if that does the trick.

Tested and confirmed working. I merged the two associated Pull Requests.

@jaswsinc Thanks so much for taking care of this! :-)
