### ISSUE TITLE
Refactor: Autoloader and Abstract Base

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache#350]
In the future, it would be great if Quick Cache could support class autoloading, and if we had an abstract base class to work from, in addition to the `\quick_cache\share` class.

- [ ] Add class autoloader and reorganize class files into `includes/classes`.
- [ ] Create a base abstraction for all other classes.
- [ ] Add magic methods to the base abstraction to assist with utility access.

_An example of these framework enhancements can be found in the [Comment Mail plugin](https://github.com/websharks/comment-mail), which was based on the framework established for Quick Cache Pro, and then enhanced further to include the above._

**Comment by raamdev** [comment]
@jaswsinc This issue can be closed after the recent refactoring that went into ZenCache Pro, correct?

**Comment by jaswrks** [comment]
Yes, you are absolutely right. Closing.
