### ISSUE TITLE
Clear/Wipe on Non-Network Multisite via `$table_prefix`

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache#354]
On a non-network multisite installation, it would be preferable to have the "clear" functionality work more like a full wipe; or perhaps expose the QC "wipe" option whenever `$table_prefix` is not `wp_` and/or changes from one host to the next.

Currently, clearing the cache does not really work as one would expect on a non-network MS installation, so-to-speak. Referencing: http://codex.wordpress.org/Editing_wp-config.php#table_prefix

**Comment by jaswrks** [comment]
@raamdev I think this can be closed now.

**Comment by raamdev** [comment]
@jaswsinc Copy that. Thanks!
