### ISSUE TITLE
Saving Post as Draft Purges XML Sitemaps

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#368]
### Steps to reproduce this issue

- In **Dashboard → Quick Cache → Plugin Options → Clearing the Cache** make sure that _Auto-Clear "XML Sitemaps" Too?_ is set to **Yes**.
- Use a plugin like _Google XML Sitemaps_ to generate some XML Sitemaps and visit the sitemap URL while logged out of the Dashboard to have Quick Cache generate cache files for those XML Sitemaps
- Compose a new post, add some tags, select a category, and then click "Save Draft"

This results in the XML Sitemap cache files being unnecessarily purged:

![2014-11-19_16-25-34](https://cloud.githubusercontent.com/assets/53005/5114723/4ae78368-7009-11e4-9e7e-53a62749e7f4.png)

**Comment by jaswrks** [comment]
This has been fixed in my development branch. See commit reference above.
~ I'll submit a PR for this soon. Still working on other improvements.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix**: Saving a Post as a Draft was incorrectly purging XML Sitemap cache files. See [Issue #368](https://github.com/websharks/zencache/issues/368).

**Comment by jaswrks** [comment]
@raamdev I think this can be closed now.
