### ISSUE TITLE
Feature Request: URI Exclusion Patterns for Quick Cache Lite

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#377]
There have been _many_ requests to have the **URI Exclusion Patterns** feature available in Quick Cache Lite. This seems like a fairly basic feature and, if I remember correctly, it was previously available in Quick Cache Lite before the major rewrite in late 2013. 

I agree with moving this feature to the Lite version and will track progress towards that in this issue.

**Comment by eurobank** [comment]
Any plans to include that any time soon ?

Thanks

**Comment by raamdev** [comment]
URI Exclusion Patterns have been added to ZenCache Lite! The next release of ZenCache Lite will include this previously Pro-only feature.

If you're interested in testing a beta release of ZenCache before the next version comes out, please sign-up to be a beta tester [here](http://zencache.com/r/zencache-beta-testers-list/). See also the [current beta release announcement](http://zencache.com/zencache-v150605-release-candidate/).
