### ISSUE TITLE
Feature Request: Clear Cache Button to clear Cache for Current Page

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#380]
It would be nice to have either an additional button--or to modify the Clear Cache button itself to support multiple options--to allow for clearing the cache for only the current page, i.e., if a site administrator was logged in and visiting a page on the site, it would be nice to have a way of allowing the admin to tell ZenCache to clear the cache for only that page.

Things we'll need to take into consideration:

- Would this clear only the regular cache served to non-logged in users, or would it clear all possible cached variations for that page (including versions that might have been built using a version salt).
- How will this work for Multisite installations?

---

Also note that it should be possible to clear the Home Page cache via this same mechanism (i.e., visit the Home Page logged in as an Admin and click the new "Clear Current Page" button to clear the cache for the Home Page). Related: https://github.com/websharks/zencache/issues/519

**Comment by lkraav** [comment]
+1, this is definitely a real need. Since clearing a page's cache is only a one-liner, what's keeping this from prcoeeding?

I don't understand the "multisite installation" question. What potential issues does this refer to?

**Comment by raamdev** [comment]
@lkraav Thanks for the +1. There was a lot of work that recently went into improving multisite support in ZenCache, so this should be rather straightforward even for multisite.

@jaswsinc Any thoughts on this feature request?

**Comment by jaswrks** [comment]
Sounds pretty straightforward, yes. The functionality is already there, we just need a UI for it. My feeling is that ZenCache could use a split button in the admin bar, so that a dropdown menu can be presented with this and perhaps some other options too. We just finished some work on this with the stats system now in the admin bar (dev branch only at the moment), but we could come back in and take a look at improving it some more.

**Comment by lkraav** [comment]
I guess the main issue is "what is a page" logic. Archives etc need to be detected correctly.

I'm also thinking "Clear Page" should be the primary one-click button, with Clear Cache appearing in a dropdown. Clear Page seems like to less expensive way to operate first in majority of use cases, but this is based on anecdotal data.

**Comment by raamdev** [comment]
One thing to keep in mind with changing the way that Clear Cache button works/looks in the Admin Bar is that there are 50,000+ sites out there, with _many_ longtime users of ZenCache (previously Quick Cache) who may not be expecting a sudden change in such a core piece of the ZenCache UI, so we'll need to take that into consideration when designing the new "drop down" menu w/ options. Perhaps there could even be an option to revert to the single-button UI, with options for which button appears there (e.g., Clear Cache or Clear Current Page).

**Comment by raamdev** [comment]
A new feature added in https://github.com/websharks/zencache/issues/596#issuecomment-152786080 that will be released with the next version of ZenCache Pro closes this issue. There's now a Clear Cache sub-menu in the Admin Bar that allows clearing the cache for the Current URL:

![2015-10-31_21-01-56](https://cloud.githubusercontent.com/assets/53005/10866843/4f66c152-801a-11e5-8da7-07eec956f85f.png)
