### ISSUE TITLE
Processes are Frequently Waiting for a Mutex Lock (LiteSpeed)

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#391]
The following bug report was opened by @LittleBastard77 in websharks/html-compressor#51: 

---

> I am using the latest version of quick cache pro to date and wordpress 4.
> 
> I enabled HTML compression last night with default options. Some tests showed improvement in speed. However this afternoon the site was extremely slow to the point that I got alerts that it was offline.
> 
> I opened a ticket with support and they sent me this. After struggling renaming the quick cache plugin directory back and forth so I could disconnect users and get the speed needed to avoid a timeout I was able to disable the HTML compression and all got back to normal again.
> 
> The supportsperson sent me the data below (I changed some names on the data for safety). If you need more detailed information, please, be very specific so I can relay the request to support or even get the log files from cpanel myself. 
> 
> Thanks.

```
root@host [/usr/local/apache/domlogs]# w
11:01:45 up 13 days, 11:31, 1 user, load average: 7.66, 6.68, 5.65

This is due to PHP executing for EXAMPLE.com:

nobody 5907 1.8 0.3 104888 44112 ? Sl 09:09 2:04 \_ litespeed (lshttpd)
cpanelaccount 13645 10.4 0.7 213984 86244 ? S 10:55 0:38 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13673 18.2 0.7 214448 86376 ? S 10:56 0:55 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13762 11.5 0.7 214380 86712 ? S 10:58 0:24 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13765 4.3 0.6 211824 85596 ? S 10:58 0:09 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13840 13.3 0.7 212608 86448 ? S 10:59 0:20 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13842 29.1 0.7 217224 88568 ? S 10:59 0:42 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13858 6.7 0.7 213144 86688 ? S 10:59 0:07 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13924 14.9 0.7 212888 86628 ? S 11:00 0:14 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13989 7.7 0.7 214176 88428 ? S 11:00 0:07 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13990 46.6 0.6 213432 85488 ? S 11:00 0:42 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13991 9.8 0.7 215216 88588 ? S 11:00 0:08 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13992 8.0 0.7 217140 91368 ? S 11:00 0:06 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 13994 17.7 0.7 213912 88148 ? S 11:00 0:14 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14009 9.7 0.7 214888 87916 ? S 11:00 0:06 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14014 12.4 0.7 221348 94932 ? S 11:00 0:07 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14016 5.0 0.7 213660 87896 ? S 11:00 0:02 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14020 13.3 0.8 234968 108008 ? R 11:00 0:06 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14028 5.1 0.7 212940 86828 ? S 11:01 0:02 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14263 4.9 0.6 212100 85848 ? S 11:01 0:01 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14264 14.2 0.7 212988 86320 ? S 11:01 0:04 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14267 12.8 0.6 211908 85600 ? S 11:01 0:02 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14320 11.5 0.6 211356 84840 ? S 11:01 0:01 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14325 15.6 0.6 212176 84996 ? S 11:01 0:00 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14329 42.0 0.6 212644 85996 ? S 11:01 0:01 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
cpanelaccount 14330 45.6 0.6 211400 85016 ? S 11:01 0:01 | \_ lsphp5:/home/cpanelaccount/public_html/index.php
```

>  When I strace one of these running PHP processes, it appears that the Quick Cache plugin is causing problems. The processes are frequently waiting for a mutex lock created by this plugin.

---

It sounds like this might be related to recent changes to Cache Locking in Quick Cache and I'd like to test Quick Cache against the LiteSpeed web server to verify that are no obvious issues with Quick Cache and LiteSpeed.

Note that @LittleBastard77 was running Quick Cache Pro v141231 at the time of this issue.

**Comment by jaswrks** [comment]
@LittleBastard77 I'm taking a closer look at this now, and I wanted to see if you could confirm that your installation of PHP has the [cURL extension](http://php.net/manual/en/book.curl.php) installed?

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: Improved HTML Compressor handling related to Connection Failures/Wait State. Props @LittleBastard77 @jaswsinc. See [Issue #391](https://github.com/websharks/zencache/issues/391).

**Comment by raamdev** [comment]
**ZenCache Pro v151002** has been released and includes changes from this GitHub Issue. 

See the [ZenCache Pro v151002 release announcement](http://zencache.com/zencache-pro-v151002-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#391).
