### ISSUE TITLE
Fork: QC to ZC Migration (Codebase)

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache#5]
Referencing: https://github.com/websharks/zencache.com/issues/4 I will use this issue to track progress on the migration (in the codebase) from QC to ZC; for both the lite and pro editions.

- [x] Rename occurrences of `quick-cache`, `quick_cache`, `Quick-Cache`, `QUICK_CACHE`, etc; to ZenCache equivalents.
- [x] Add back compat. for `QUICK_CACHE_` constants?
- [x] Add back compat. for `quick_cache` hooks/filters.
- [x] Add back compat. for old cache directory location.
- [x] We also need to add support for both zcAC and qcAC; along with zcABC and qcABC.
- [x] Add back compat. for older API class that used `quick_cache` for the class name.
- [x] Update images that contain QC logos and/or the text `Quick Cache`.
- [x] Update wiki links to point them to redirects at websharks-inc.com.
- [x] Update hard-coded strings with `Quick Cache` or `ZenCache`; or any variation to something dynamic; i.e. so we can change this again easily if we rebrand the software.
- [x] Add back compat. for option keys in WordPress.
- [x] Update images in the `assets` directory; i.e. the WP banner, icons, etc.
- [x] Add back compat. for CRON jobs.
- ~~Update plugin screenshots.~~ **Moved this to #6**
- [x] Add automatic QC uninstaller on ZC upgrade.
- ~~Add product page at websharks-inc.com so that automatic updates work as expected; i.e. we need to swap the existing Quick Cache product for ZenCache. The following URL needs to exist: http://www.websharks-inc.com/product/zencache/ ~ Along w/ this, we also need to update the existing CCAPS associated with customers that have purchased Quick Cache Pro; where it's now called ZenCache Pro.~~ **Moved this to websharks/zencache.com#4**
- ~~Create page http://www.websharks-inc.com/zencache-beta-testers/ or update the redirect I created that points to this location; i.e. https://www.websharks-inc.com/wp-admin/post.php?post=1935&action=edit~~ **Moved this to websharks/zencache.com#4**
- ~~The Quick Cache mailing list at MailChimp should be renamed to ZenCache. Or, if a new list is created, please update the redirect I created here: https://www.websharks-inc.com/wp-admin/post.php?post=1935&action=edit~~ **Moved this to websharks/zencache.com#4**
- [x] Regenerate POT translation files.
- [x] Detect presence of Quick Cache and do not allow both plugins.
- [x] Add submodule for `wp-php-rv`; i.e. use `wp-php-rv` in favor of `wp-php53`.
- [x] Add back compatibility in ZenCache for global variable references that previously used the `quick_cache` namespace, e.g. `$GLOBALS['quick_cache__advanced_cache']` and the like (see https://github.com/websharks/zencache/issues/5#issuecomment-68192428)
- [x] ZenCache to automatically "deactivate" Quick Cache plugin on first install.

**Comment by raamdev** [comment]
@jaswsinc This issue looks ready to close, agreed?

**Comment by jaswsinc** [comment]
Agreed.
