### ISSUE TITLE
Minor UI Revamp before ZC Launch

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache#6]
@jaswsinc writes...
> Maybe it would be good to change the colors up a little and just try to enhance the existing look n' feel when we release ZenCache

@raamdev writes...

> Yes, I agree on this too. I think even just changing the color scheme a bit would be a good idea. Maybe more silver? Something that will fit nicely with the new logo. The current green/purple color scheme really doesn't look right with the new ZenCache logo.

---

I'm going to hold off on updating the `assets/screenshot*` files that I mentioned in #5  until this is done.

**Comment by raamdev** [comment]
Marking this as closed. The UI and the menu icon look good to me.
