### ISSUE TITLE
Feature Request: Option to choose which WordPress roles have permission to clear cache

### ISSUE THREAD

**Issue by danielmt2k** [websharks/zencache#68]
Hi,

In a multisite environment, not all the users publishing content should be an administrator.

So, it would be great to add the possibility for the non-admin users (i.e., an editor) to have the button to clean the cache for their website.

Regards.

**Comment by andreaarden** [comment]
I used the WpFront User Role Editor plugin on a client site to create a "Custom" role that can update widgets but not install/update plugins, etc.  Being able to enable the Clear Cache button for non-admin and "Custom" roles is definitely needed. Thanks for considering it!

**Comment by jaswsinc** [comment]
@andreaarden Copy that. Thanks for the +1 here! :-)

### Short-Term Solution that Might Help Some

Quick Cache exposes an API method that makes this possible.
Here is a quick example of how to handle this in PHP code.

```php
<?php
quick_cache::clear();
```

**TIP:** If you want to make it possible to call this remotely, you might put together a [Must-Use](http://codex.wordpress.org/Must_Use_Plugins) plugin in WordPress, where the MU plugin is just one file that exposes this functionality.

Create the following directory and file:
`/wp-content/mu-plugins/qc-clear.php`

```php
<?php
add_action('init', function()
{
    if(!empty($_GET['qc_clear']) && $_GET['qc_clear'] === 'my-secret-key')
     { quick_cache::clear(); exit; }
});
```

Now you would be able to call upon the Quick Cache API remotely by including your secret key.
`http://example.com/?qc_clear=my-secret-key`

**Comment by andreaarden** [comment]
Thank you very much for the solution!  I tried it, but it didn't work for me.  I'm not much of a coder, so I might have done something wrong.  

First, I logged in and made a change to the widgets and logged out without manually clearing the cache.  (I think QCP does not automatically update the cache for changes to widgets.  Is that correct?)

I copied the code above as is (no closing PHP tag) and substituted my QCP license code inside the single quotes for "my-secret-key".  I saved the file using Notepad++ as qc-clear.php and ftp'd it to the wp-content/mu-plugins directory.  

Then I entered http://[my URL].com/?qc_clear=[QCP license code] in my browser and pressed return.  The screen went white and no message appeared.  I opened another tab pointing to the site and pressed refresh, but the change was still not visible. 

Did I miss something?

**Comment by raamdev** [comment]
@andreaarden I think @jaswsinc made a mistake in the code:

```php
quick_cache::clear()
```

Should be:

```php
quick_cache::clear_cache()
```

Can you try updating the code to use `quick_cache::clear_cache()` and try again?

**Comment by jaswsinc** [comment]
@raamdev writes...

> @jaswsinc made a mistake in the code:

It is `quick_cache::clear()`. This is part of the QC API. However, if you were calling this against the global object, it would be `$GLOBALS['quick_cache']->clear_cache()`.

Referencing: https://github.com/websharks/quick-cache/blob/000000-dev/quick-cache/includes/api-class.php#L73

@andreaarden writes...

> Then I entered http://[my URL].com/?qc_clear=[QCP license code] in my browser and pressed return. The screen went white and no message appeared.

That's to be expected. Just a white screen. I went ahead and updated the code sample above though, so that it will exit with `exit('cache cleared');`. So now you should get `cache cleared` on that white screen; just to make it a little more friendly.

> I opened another tab pointing to the site and pressed refresh, but the change was still not visible.

Are you running a multisite network by chance? If so, please be sure to call upon the script from that particular child blog; e.g. `http://child.example.com/?qc_clear=[secret key]`. Or, in the case of a sub-directory install: `http://example.com/child/?qc_clear=[secret key]`

**Comment by andreaarden** [comment]
Tried it, but got the error below:

*Fatal error*: Call to undefined method quick_cache::clear_cache() in
*/home/mysticco/public_html/oliver2/wp-content/mu-plugins/qc-clear.php* on
line *5*

**Comment by andreaarden** [comment]
Thanks, I'll try that shortly.  I have to go off-line for a bit.  No
multisite; it's a subdomain.

**Comment by andreaarden** [comment]
Thank you again.  I tried the revised code.  Although the "cache cleared" message appeared, the cache didn't seem to actually clear because the widget change didn't display on the refreshed page. (I tried it repeatedly.)  However, when I tried the same PHP script on another site hosted on a different server (using a similar widget scenario), it worked perfectly. 

The site where it failed is hosted on LIteSpeed.  Could that or a PHP security setting be causing it to fail?  I don't have a problem clearing the cache manually from inside the WP backend.

**Comment by jaswsinc** [comment]
> The site where it failed is hosted on LIteSpeed. Could that or a PHP security setting be causing it to fail?

No, I don't think so. LiteSpeed in and of itself should not impact this. However, you might check with your hosting company, or run a server scan, just to see if LiteSpeed is running with any other caching functionality at a higher level. Your comment suggests that it is; i.e. that it's not updating even after you clear the WordPress cache. There's another cache somewhere, I'm betting.

> I don't have a problem clearing the cache manually from inside the WP backend.

That's really odd. The routine in the Dashboard is the very same one that I posted above. The only difference would be that it's not attached to any other hooks/filters. Some hosting companies may hook into Quick Cache (or WordPress itself) in various ways that will impact high-level caches also. So again, asking your company, "What sort of caching occurs outside of WordPress? OpCode Cache? HTML cache? Anything?" may give you some insight.

**Comment by danielmt2k** [comment]
Any update on this request? Is it in your future release?

**Comment by raamdev** [comment]
@danielmt2k Yes, this is still near the top of our list of new features to work on. It's currently part of the Next Release milestone (targeted for April 1st), however we always prioritize working on bugs before new features so I can't make any promises.

**Comment by TF28** [comment]
+1 for this feature!
Many Thanks!

**Comment by JonasVorwerk** [comment]
+1 for clear the cache by editors!

**Comment by jemoreto** [comment]
+1 for clear the cache by editors!
Cheers

**Comment by phwconz** [comment]
+1 also for allowing Clear Cache for Editors.
Is there any update on when this will be implemented?

**Comment by raamdev** [comment]
@phwconz This feature request has been made a priority feature for an upcoming development cycle, so it shouldn't be long before you see this in ZenCache. :-)

**Comment by andreaarden** [comment]
Yeay!  Will the ZenCache feature work for custom roles too?  I use a WP
plugin to create a custom role for clients, usually not based on the editor
role.

**Comment by raamdev** [comment]
> Will the ZenCache feature work for custom roles too?

@andreaarden Yes, we'll make that possible. :-) 

## 

It looks like we should be able to use the WordPress [`get_editable_roles()` function](http://codex.wordpress.org/Function_Reference/get_editable_roles) to retrieve a list of roles that is then presented to the site owner as a series of checkboxes, allowing the site owner to select which roles should be able to see and use the "Clear Cache" button in the toolbar.

**Comment by danielmt2k** [comment]
Hi,

Has this feature been added to ZenCache?

Regards.

**Comment by jemoreto** [comment]
Waiting for this feature too!!
Thanks

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **New Feature:** It's now possible to specify which WordPress Roles/Capabilities are allowed to clear the cache from the WordPress Admin bar. A new option inside _Dashboard → ZenCache → Plugin Options → Manual Cache Clearing_ allows specifying a comma-delimited list of Roles and/or Capabilities under, "Also allow others to clear the cache from their Admin Bar?". If a user has an allowed Role/Capability, they will see the "Clear Cache" button in their Admin Bar. This feature is also compatible with WordPress Multisite Networks, allowing a Network Administrator to define which Child Site roles should allow a Child Site user to see the "Clear Cache" button for their Child Site. Props @danielmt2k @jaswsinc. See [Issue #68](https://github.com/websharks/zencache/issues/68).

**Comment by danielmt2k** [comment]
Thanks Raam for listening to suggestions!!! Great!!!

**Comment by raamdev** [comment]
**ZenCache Pro v151002** has been released and includes changes from this GitHub Issue. 

See the [v151002 release announcement](http://zencache.com/zencache-pro-v151002-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#68).
