### ISSUE TITLE
Feature Request - Mobile User Agent List

### ISSUE THREAD

**Issue by VR51** [websharks/zencache#72]
Not an issue for responsive theme designs but a major (and comical) issue for websites using mobile themes: sometimes a cached mobile themed page is served to desktop users instead of the desktop version of a page. This seems to be caused by the cache file for a page being generated when a mobile visitor views a page.

I use user agent referral pattern lists to prevent caching of pages served to mobile visitors. Would be really nice to not need to manually add that list in every site that I install Quick Cache into. Any chance of checkbox being added such as 'Do not serve cache files to mobile phones' and 'Do not serve cache files to tablets'.

**Comment by raamdev** [comment]
@VR51 Great idea! I will accept this feature request and add it to my TODO list.

Here's the list I have for mobile User-Agent Exclusion:

```
w3c_validator 
iPhone**
iPod**
Android**
BB**Mobile**Safari 
BlackBerry**
IEMobile/10.0**Touch 
IEMobile/7.0 
IEMobile/9.0 
webOS
```

Is there anything you'd add? What do you suggest for the "tablet" exclusion list?

**Comment by raamdev** [comment]
Closing this issue in favor of #471, which will add full support for mobile devices by adding a "Mobile Mode" to ZenCache.
