### ISSUE TITLE
Feature Request: Multisite Option to Allow Individual Site Admins to "Clear Cache" 

### ISSUE THREAD

**Issue by twicealive** [websharks/zencache#78]
Regarding Quick Cache Pro, please consider including the option to allow Site Admins to "Clear Cache" on their individual multisites for the multisite network. 

Thank you,
Michael

**Comment by raamdev** [comment]
Closing this issue in favor of https://github.com/websharks/zencache/issues/68, which includes a feature request for not just Multisite but also Single-site.
