### ISSUE TITLE
Feature Request: Total Cache Size on Disk Statistics

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache#83]
I'd like to see a graphical disk usage meter in the Dashboard (perhaps even in the admin bar too)... which shows the current total disk space consumed by Quick Cache at the present time. Or, if that's not feasible (i.e. too resource intensive) it could be updated every X minutes or so.

I think it should be a pro feature myself.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **New Feature!** Cache Statistics is a completely new ZenCache Pro feature that will help site owners better understand their WordPress site cache. An easy-to-access Cache Stats menu button in the Admin Bar is accompanied by a whole new page that shows Current Cache Totals (including total number of cache files and total size of cache on the disk), Current Disk Health (including total disk capacity and total available), Current System Health (including memory usage and load average), and two beautiful Polar Area pie charts that show you both current and historical data on Cache File Counts and Cache File Sizes with a 30-Day High, Current Total, Page Cache total, and HTML Compressor total for each chart. Props to @jaswsinc. See [Issue #83](https://github.com/websharks/zencache/issues/83).

**Comment by raamdev** [comment]
**ZenCache Pro v151002** has been released and includes changes from this GitHub Issue. 

See the [v151002 release announcement](http://zencache.com/zencache-pro-v151002-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#83).
