### ISSUE TITLE
white page when activating comet-cache plugin

### ISSUE THREAD

**Issue by kevinmurphy777** [websharks/zencache#882]
Hello, I just installed Autoptimize. They recommended a caching plugin like Comet-cache, and I dutifully complied and downloaded the Comet-Cache plugin as well. 
Now my website is just a white screen. See it for yourself at [TermLife316.com](url)

In similar articles I saw where Raam Dev recommended a manual uninstall of Comet-cache, and then reinstalling.  **_I am just an insurance agent and not a coding guy._**
I don't have the first clue how to go about doing all of that FTP stuff. I'll just make things worse!
How does the "little guy" get stuff like this repaired?
thanks
Kevin

**Comment by raamdev** [comment]
Hi Kevin,

If you're running into trouble with your site and you're not sure how to fix it, I recommend reaching out to your web hosting company. They can at least point you in the right direction. FTP is not something particular to WordPress or Comet Cache, but rather it's all about connecting to your web server to add/remove files—your web hosting company would be best equipped to help you there. You can point them to [these manual uninstallation instructions](https://cometcache.com/kb-article/how-do-i-uninstall-comet-cache/#toc-86754ab8) if necessary.

If you want help specifically with WordPress-related activities, I recommend the [WordPress Support Forums](https://wordpress.org/support/) where there are lots of volunteers on hand.

----

We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [Community Forum](https://cometcache.com/r/community-forum/) (for Comet Cache Lite) or open a [Support Ticket](https://www.websharks-inc.com/support/?product=comet-cache&request_type=trouble_ticket) (Comet Cache Pro). Thank you! :)

**Comment by kevinmurphy777** [comment]
I actually found another way to delete,,,, that was hidden in the bowels of another comet-cache memo that did not involve FTP.
So I deleted comet-cache....
the website is back (*huzzah*) but now my header image (video) is gone.
It just never ends!

Kevin

**Comment by kevinmurphy777** [comment]
thanks Raam.

kevin


*Kevin Murphy*   Founder and Principal, TermLife316.com
Phone: *925-588-8373* <925-588-8373>
Email: *kevin@TermLife316.com* <kevin@TermLife316.com>
Website: *TermLife316.com* <http://TermLife316.com>
Today's quote: *Could your family keep their home, afford the bills, & go
to college if you die? (if I ask you I'll have to insure you)*
[image: photo]
<http://twitter.com/whatifyoucroak>  <http://termlife316.com/get-quote/>
