### ISSUE TITLE
When reseting cache WP froze

### ISSUE THREAD

**Issue by uhlhosting** [websharks/zencache#906]
I run WP 4.8 and latest version of cc. When I click Clean ALL or WIPE, since I rn in multisite. I get simply a 100%CPU on Server, and all stucked. How can I fix this?

**Comment by raamdev** [comment]
@uhlhosting We reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [Community Forum](https://cometcache.com/r/community-forum/) (for Comet Cache Lite) or open a [Support Ticket](https://cometcache.com/support/) (Comet Cache Pro). Thank you! :)
