### ISSUE TITLE
Stats Page redirect to 503 error page

### ISSUE THREAD

**Issue by GermontZ** [websharks/zencache#911]
Hello!

I immediately installed the Release Candidate v170808-RC, and everything worked just fine for a few days on my low traffic site - 100 unique visitors /a day.
But yersteday I visited the stats page, and redirects me to www .example.com/503.shtml/ page.
I cleaned the cache folder previous day and everything went fine, I preloaded 1360 cached files according to the stats page.
Error log was not updated this month.
As my cpanel licence it's expired, I can't enable memcahe, and don't know if it's really working or not for my installation.

Now you tell me what details you need.

**Comment by GermontZ** [comment]
the stats page came back after two days. Strange!

**Comment by raamdev** [comment]
@GermontZ Thanks for the report. This sounds to me like it might have been a corrupted browser cache issue. If you see this again and clearing your browser cache does not solve the issue, please let us know.
